### PR TITLE
fix mistyped command

### PR DESCRIPTION
**Pull request by zeke**
👋 Hey @dominictarr thanks for making this lib. 

This PR fixes a mistyped command in the code, and now it Works On My Excel File!

### CODE REVIEW

**Comment by zeke** [comment]
Friendly bump. Happy to help maintain this module if you don't have the time for it.

**Comment by dominictarr** [comment]
great, you are now npm owner. also will transfer this to you.
Thanks you for adopting this baby!

**Comment by dominictarr** [comment]
oh it won't let me transfer it to you because you already have a fork. anyway you can just set the npm link to be your fork not mine.

**Comment by zeke** [comment]
grazie!

**Comment by dominictarr** [comment]
you are also welcome to any of my other excell related modules, just say the word.

**Comment by zeke** [comment]
```
$ np patch
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using npm
 ✔ Running tests
 ✔ Bumping version using npm
 ✔ Publishing package
 ✔ Pushing tags

 simple-xlsx 1.1.1 published 🎉
```

**Pull request closed without merging**
